NOIR = (0, 0, 0)
BLANC = (255, 255, 255)

TUILE_TAILLE = 30
TUILE_NOMBRE = 25
SCORE_HAUTEUR = 32

LARGEUR = TUILE_TAILLE * TUILE_NOMBRE
HAUTEUR = TUILE_TAILLE * TUILE_NOMBRE + SCORE_HAUTEUR

POINT_UNITE = 1

